/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* Define if you have unistd.h */
#define CHROOT 1

/* Define if you have pwd.h */
#define CHUID 1

/* Define to 1 if you have the <alloca.h> header file. */
#define HAVE_ALLOCA_H 1

/* Define to compile in auth URL support code */
/* #undef HAVE_AUTH_URL */

/* Define if you have libcurl. */
/* #undef HAVE_CURL */

/* Define to 1 if you have the <curl/curl.h> header file. */
/* #undef HAVE_CURL_CURL_H */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the `endhostent' function. */
#define HAVE_ENDHOSTENT 1

/* Define to 1 if you have the `getaddrinfo' function. */
#define HAVE_GETADDRINFO 1

/* Define if you have the getnameinfo function */
#define HAVE_GETNAMEINFO 1

/* Define to 1 if you have the `inet_aton' function. */
#define HAVE_INET_ATON 1

/* Define to 1 if you have the `inet_pton' function. */
#define HAVE_INET_PTON 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `localtime_r' function. */
#define HAVE_LOCALTIME_R 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define if you have nanosleep */
#define HAVE_NANOSLEEP 1

/* Define if you have libogg installed */
#define HAVE_OGG 1

/* Define to 1 if you have the `poll' function. */
#define HAVE_POLL 1

/* Define if you have POSIX threads libraries and header files. */
#define HAVE_PTHREAD 1

/* Define to 1 if the system has the type `pthread_rwlock_t'. */
#define HAVE_PTHREAD_RWLOCK_T 1

/* Define to 1 if you have the <pwd.h> header file. */
#define HAVE_PWD_H 1

/* Define if you have the sethostent function */
#define HAVE_SETHOSTENT 1

/* Define to 1 if the system has the type `socklen_t'. */
#define HAVE_SOCKLEN_T 1

/* Define if Speex support is available */
/* #undef HAVE_SPEEX */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if the system has the type `struct ovectl_ratemanage_arg'. */
#define HAVE_STRUCT_OVECTL_RATEMANAGE_ARG 1

/* Define to 1 if `ss_family' is member of `struct sockaddr_storage'. */
#define HAVE_STRUCT_SOCKADDR_STORAGE_SS_FAMILY 1

/* Define to 1 if you have the <sys/select.h> header file. */
#define HAVE_SYS_SELECT_H 1

/* Define to 1 if you have the <sys/socket.h> header file. */
#define HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/uio.h> header file. */
#define HAVE_SYS_UIO_H 1

/* Define if Theora support is available */
/* #undef HAVE_THEORA */

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define if you have winsock2.h on MINGW */
/* #undef HAVE_WINSOCK2_H */

/* Define to 1 if you have the `writev' function. */
#define HAVE_WRITEV 1

/* Define to 1 if you have the `xsltSaveResultToString' function. */
#define HAVE_XSLTSAVERESULTTOSTRING 1

/* Name of package */
#define PACKAGE "icecast"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "icecast@xiph.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "Icecast"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "Icecast 2.3.0.rc3"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "icecast"

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.3.0.rc3"

/* Define to necessary symbol if this constant uses a non-standard name on
   your system. */
/* #undef PTHREAD_CREATE_JOINABLE */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to compile in YP support code */
/* #undef USE_YP */

/* Version number of package */
#define VERSION "2.3.0.rc3"

#ifndef HAVE_SOCKLEN_T
typedef int socklen_t;
#endif


/* Define to include GNU extensions to POSIX */
#define _GNU_SOURCE 1

/* Define if you have POSIX and XPG specifications */
/* #undef _XOPEN_SOURCE */

/* define if va_copy is not available */
/* #undef va_copy */
